---
platform: linux

image_resource: 
  type: docker-image
  source:
    repository: ebroberson/pool-resource-test
    
inputs:
- name: pool-resource
  path: gopath/src/github.com/ebroberson/pool-resource

outputs:
- name: built-resource

run:
  path: gopath/src/github.com/ebroberson/pool-resource/ci/build
