#!/bin/sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

. $(dirname $0)/common.sh

payload=$(mktemp $TMPDIR/pool-resource-request.XXXXXX)
cat > $payload <&0
load_pubkey $payload
configure_https_tunnel $payload
configure_credentials $payload

git_config_payload=$(jq -r '.source.git_config // []' < $payload)

configure_git_global "${git_config_payload}"

_terminate() {
  kill -TERM "$child" 2>/dev/null
}

trap _terminate TERM

/opt/go/out $1 >&3 < $payload &

child=$!
wait "$child"
