#!/bin/bash
# vim: set ft=sh

set -eu

export TMPDIR=/tmp
export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

cd $GOPATH/src/github.com/concourse/pool-resource

export GOPATH=${PWD}/Godeps/_workspace:$GOPATH
export PATH=${PWD}/Godeps/_workspace/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

CGO_ENABLED=1 ginkgo -race -r -p "$@"

go build -o built-out ./cmd/out
