#!/bin/bash
# vim: set ft=sh

set -e -u -x

export TMPDIR=/tmp
export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

BUILD_DIR=$PWD/built-resource

cd $GOPATH/src/github.com/concourse/pool-resource

export GOPATH=${PWD}/Godeps/_workspace:$GOPATH
export PATH=${PWD}/Godeps/_workspace/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

CGO_ENABLED=1 ginkgo -race -r -p "$@"

cp -a test/ assets/ Dockerfile $BUILD_DIR
go build -o $BUILD_DIR/built-out ./cmd/out
