#!/bin/bash -exu
# vim: set ft=sh

export TMPDIR=/tmp
export GOPATH=${PWD}/gopath
export GOBIN=${GOPATH}/bin
export PATH=${GOBIN}:${PATH}

BUILD_DIR=${PWD}/built-resource

go install github.com/concourse/pool-resource/vendor/github.com/onsi/ginkgo/ginkgo

pushd ${GOPATH}/src/github.com/concourse/pool-resource > /dev/null
  CGO_ENABLED=1 ginkgo -race -r -p "$@"

  cp -a test/ assets/ Dockerfile ${BUILD_DIR}
  go build -o ${BUILD_DIR}/built-out ./cmd/out
popd > /dev/null
